### ISSUE TITLE
Copy Paste from pdf gives corruption in character

### ISSUE THREAD

**Issue by ashakoshti1988** [sphilee/jsPDF-CustomFonts-support#11]
Hi @sphilee copying from pdf gives character corruption..is it the issue because of hex code?
what can be the solution?

**Comment by ashakoshti1988** [comment]
hi @sphilee  please help.as i am totally stuck..when export in pdf and data from exported pdf gives corruption.

**Comment by olsn** [comment]
Same issue here, where you able to solve this somehow? - Text is displayed correctly, but copy/pasting to somewhere else just displays random data - might this be some UTF16 issue?

**Comment by sphilee** [comment]
https://github.com/sphilee/jsPDF-CustomFonts-support/tree/v2

Can you check this branch?
I'm now fixing this bug.

**Comment by olsn** [comment]
I'm testing it right now

**Comment by olsn** [comment]
I just noticed in your sourcecode that multiline-text is not yet implemented for this fix, are you already working on this?
Also the width- and height-calculation does not seem to work correctly, are those two issues related?

**Comment by sphilee** [comment]
@olsn Could you give me some test code which is not working in some cases?

**Comment by olsn** [comment]
I've added a quick demo here: http://ablage.ndgmr.com/jspdf_cf/test.html
The relevant code for this demo is the following:
```
        doc.addFont('ROBOTO_REGULAR.ttf', 'Roboto', 'normal', 'MacRomanEncoding');

        doc.setFont('Roboto');
        doc.text(15, 60, ['Hello Test 123 ∑ %Δ', 'this should be in a new line, but it is not']);

        doc.setFont('Helvetica');
        doc.text(15, 120, ['Hello Test 123 ∑ %Δ', 'this is in a new line, but with Helvetica special chars won\'t work']);
```

**Comment by sphilee** [comment]
[jsPDF-splitText.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/1370110/jsPDF-splitText.zip)

Can you test it with this one? I think Helvetica fonts and default fonts can not express Σ, Δ.


![image](https://user-images.githubusercontent.com/20538040/31363316-a4291638-ad98-11e7-9574-c0a620ab9d63.png)

**Comment by olsn** [comment]
Awesome, it works!! You are the best!
Seriously send me your paypal or bitcoin/ether-address, I'd like to buy you a coffee. (you can send it to pure.onh@gmail.com if you don't want to share it publicly)

(The issue that the default fonts cannot express special character is know, yes)

**Comment by olsn** [comment]
I've implemented a few changes:
- alignment did not work, so I made this work
- when there were texts placed close to the page-end it resulted in an endless-loop
   e.g.: pageWidth = 100; x = 95; wordWidth = 10
   => I "fixed" this by setting `maxWidth` to `99999` instead of `this.internal.pageWidth` (more like a workaround than a fix, but it caused issues with right-aligned text, guess the calculation could be deactivated there as well)

[jspdf_split+align+customFont.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/1372727/jspdf_split.align.customFont.zip)

**Comment by olsn** [comment]
One more update: The Microsoft EDGE Browser cannot render PDFs with this update - every possible other reader seems to work fine though: IE11, FireFox, Chrome, Acrobat all work fine.
I'm not sure if this an issue with the PDF or with EDGE, but looks like an issue with EDGE.

**Comment by sphilee** [comment]
@olsn Thanks for letting me know. I'll try to fix it soon.
