### ISSUE TITLE
Embedded fonts with polish characters

### ISSUE THREAD

**Issue by imkamil** [sphilee/jsPDF-CustomFonts-support#15]
Thanks for contribution. I want to asked is it support polish fonts. please confirm its very urgent

https://www.fontsquirrel.com/fonts/list/language/polish

**Comment by sphilee** [comment]
Of course we support.
![image](https://cloud.githubusercontent.com/assets/20538040/25178492/ee3b634c-2540-11e7-8297-8022a2c8ad02.png)

**Comment by sphilee** [comment]
[jsPDF-CustomFonts-support.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/933923/jsPDF-CustomFonts-support.zip)

**Comment by imkamil** [comment]
Thanks you for fast replay. You have a right it is work with this font. Can you tell me how you do this :) where are you encoder ttf font. I have someone font and i can't work it. I can send my font but on private message. All fonts types is supported?

**Comment by imkamil** [comment]
My font doesn't work. Screenshot preferences uses font on PDF
<img width="612" alt="zrzut ekranu 2017-04-20 o 18 19 45" src="https://cloud.githubusercontent.com/assets/27728177/25241442/4c8a4322-25f6-11e7-9d92-3b37c9f72559.png">

**Comment by sphilee** [comment]
https://www.giftofspeed.com/base64-encoder/
You can use this site to encode it and save it in vfs_fonts.

**Comment by Aknieshka** [comment]
Hi, I have a problem with using the functions doc.addImage() and doc.drawText() together. 
Separately works correctly. With doc.addImage( ) I can use only .doc.text(), and only with "jspdf.min.js". I don't know what to do...
