### ISSUE TITLE
How to use Custom Fonts?

### ISSUE THREAD

**Issue by idevN** [sphilee/jsPDF-CustomFonts-support#16]
I tried adding Roboto font.

`doc.addFont('Roboto-Regular.ttf', 'roboto', 'normal', 'Identity-H');    
doc.setFont('roboto');   `

But it doesn't seem to work? What is the issue here?

Also, how can I use Google Web Fonts? I read that it should be possible by converting font to base64 format but I couldn't find any working implementation or couldn't get to convert google web fonts to base64 format.

Any ideas?

**Comment by idevN** [comment]
@nahomtefera Thanks. That made the custom fonts work. But I am having the font spacing issue that you had even after using the font squirrel tool with the settings you showed.

Can you share what logic to apply when changing those settings? Also, what is the different between encoding types?

`doc.addFont("Roboto.TTF","Roboto","normal","WinAnsiEncoding");`

How to know which encoding type to choose?

**Comment by sphilee** [comment]
https://github.com/sphilee/jsPDF-CustomFonts-support/tree/v2

Can you check this branch?
I'm now fixing this bug.

**Comment by malebuffy** [comment]
I followed the above steps and get:

`jspdf.customfonts.debug.js:11984 Font does not exist in FileInVFS, import fonts or remove declaration doc.addFont('ocrb_regular.ttf')`

are there additional steps to makethis work?

**Comment by iSarahSH** [comment]
https://github.com/sphilee/jsPDF-CustomFonts-support/issues/16#issuecomment-307294932
@idevN Delete "WinAnsiEncoding" to avoid font spacing issue.

**Comment by NormanArantec** [comment]
Hi everybody! I included jspdf.customfonts.min.js, default_vfs.js and https://unpkg.com/jspdf@latest/dist/jspdf.min.js in order to use an specific ttf from my repository (OpenSans-Regular.ttf) which has '€', but pdf stills apppearing 'þÿ'. 

doc = new jsPDF();
    
    doc.addFont('{{asset('bundles/inspinia/fonts/OpenSans/OpenSans-Regular.ttf')}}', 'OpenSans-Regular', 'regular');
    doc.setFont('OpenSans-Regular');

Any clue about what I'm doing wrong.

Thank you!
