### ISSUE TITLE
Standard WinAnsiEncoding fails with € sign

### ISSUE THREAD

**Issue by erikari** [sphilee/jsPDF-CustomFonts-support#17]
but works perfectly fine with $ sign, accents, etc.
The font used is Montserrat but also other fonts such as open sans are giving the same problem.

This is what happens (it draws weird characters on all the line of text) http://prntscr.com/g4cyzq

Also, if I try to change the encoding to Identity-H the generated PDF cannot be read.

**Comment by sphilee** [comment]
https://github.com/sphilee/jsPDF-CustomFonts-support/tree/v2

Can you check this branch?
I'm now fixing this bug.
