### ISSUE TITLE
Font spacing on PDF file

### ISSUE THREAD

**Issue by nahomtefera** [sphilee/jsPDF-CustomFonts-support#2]
Hello, first of all thank you for this awesome feature!

So far the only issue I'm having is that It looks like the kerning in many fonts is way too off.  

If someone know how to fix this I will really appreacitae the help, thank you!

[![example.png](https://s30.postimg.org/h7a230ne9/example.png)](https://postimg.org/image/hk1g975nx/)

**Comment by nahomtefera** [comment]
I just found the solution. If you are having kerning (letter spacing) issues first upload your .ttf font to [Font Squirell](https://www.fontsquirrel.com/tools/webfont-generator), then check the boxes marked in red in the pictures. Press download and you will get a compressed file with a new .ttf file. Now you have to [encode to base64](https://www.giftofspeed.com/base64-encoder/) this new file and then you will be able to use your fonts without kerning issues.

[![FirstPart.png](https://s23.postimg.org/9ct86qzjv/First_Part.png)](https://postimg.org/image/nj8z1zaev/)
[![Part2.png](https://s23.postimg.org/agdcipk6z/Part2.png)](https://postimg.org/image/9e36061dj/)

**Comment by jordibartolome** [comment]
that doesn't seem to work for me :(

**Comment by nahomtefera** [comment]
@jordibartolome Hola Jordi! Estás intentando solucionar problemas con el espaciado? Qué fuente estás utilizando?

**Comment by jordibartolome** [comment]
@nahomtefera Utilizo la fuente Ashfont. El workaround que he usado ha sido escribir letra por letra y calcular la posición relativa de cada letra teniendo en cuenta el tamaño de la letra anterior. He intentado varias configuraciones de la web fontsquirrel que dijiste, pero no me ha funcionado ninguna :(

Now in english :) 
The workaround I used is to add letter by letter all the words and calculate the relative position of the next letter taking into account the width of the previous one. I couldn't find a better way!

**Comment by erikari** [comment]
Oh my god. I've spent 4 days understanding what was wrong with montserrat. In the end I was so desperate I started reading all the issues. THANK YOU Q.Q____ Finally!
I was in such a deep despair, tried changing font twice. And here was the solution!

It worked!

**Comment by joseglego** [comment]
@erikari it doesn't work for me and Montserrat, which font-weight of Monserrat are you using? And which configuration?

**Comment by joseglego** [comment]
@jordibartolome @nahomtefera I think it depends. Not all fonts works with this configuration (at least, not for me. I will try few times more)

**Comment by erikari** [comment]
@joseglego I used montserrat regular, medium and bold. I uploaded them on fontsquirrell and selected the exact same things present in the screenshot and it worked. 

The only thing that it's not working is aligning a text to the right, so I had to force this calculation in split_text_to_size to get it to work by using weights generated with a python script in fontforge. (I got help to do this very last part)

**Comment by erikari** [comment]
Here's montserrat bold so you can test it:
https://pastebin.com/5PxpZ0SS

**Comment by joseglego** [comment]
WoW! This is weird. It doesn't work.

Let me show a screenshot:
<img width="245" alt="screen shot 2017-08-10 at 2 32 39 am" src="https://user-images.githubusercontent.com/238259/29157303-4b61fc6c-7d74-11e7-8516-b74975b45cdd.png">

But thanks so much! And it looks different than my previous generated montserrat font.

**Comment by erikari** [comment]
That's not montserrat o.o 
In my case it looks like this:
![montserrat demonstration](https://image.prntscr.com/image/I-ha799RT_ygr7m-IE1Hog.png)

**Comment by joseglego** [comment]
I'm sorry! You were right! 

<img width="205" alt="screen shot 2017-08-10 at 2 42 25 am" src="https://user-images.githubusercontent.com/238259/29157614-a101261a-7d75-11e7-8a4c-753ce1015622.png">

it has some little details. But it works for me! Thanks so much, again!

**Comment by nahomtefera** [comment]
I had a lot of issues with accented vowels. The struggle is real when our
fonts don't work haha

**Comment by joseglego** [comment]
You're right @nahomtefera. It works perfect for English, I think maybe we have to play more generating the font. But the support for vowels is not cool. 

Thanks so much! Because it works. I have to pay more attention to details. But it's ok!

**Comment by erikari** [comment]
I have no problems with accented wovels such as èéàòùÈ etc. but the € sign breaks everything, I had to make a custom font to replace the simbol -.-

**Comment by sphilee** [comment]
https://github.com/sphilee/jsPDF-CustomFonts-support/tree/v2

Can you check this branch? This solves the Font spacing and € sign problem.
I'm now fixing this bug.
