### ISSUE TITLE
Thai language Support ?

### ISSUE THREAD

**Issue by xeleniumz** [sphilee/jsPDF-CustomFonts-support#21]
Hi there.
I have use js-customfonts to add THSarabunNew font , I already test with add with file base64 encrypt and add with .ttf file type when i checked console.log it show the same error. this is an error message
`
Uncaught TypeError: Cannot set property 'adler32cs' of undefined
    at t (jspdf.customfonts.min.js:102)
    at jspdf.customfonts.min.js:102
    at jspdf.customfonts.min.js:1
    at jspdf.customfonts.min.js:1
`

**Comment by sphilee** [comment]
[jsPDF-CustomFonts-support.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/1424942/jsPDF-CustomFonts-support.zip)

Would you check this? I think it supports Thai fonts.

**Comment by xeleniumz** [comment]
@sphilee thank you for fast response now it's work but i have a question. how to add custom fonts to defaultVFS ? because I'm trying to upload this file and covert it base64 with website  https://www.giftofspeed.com/base64-encoder/
but it doesn't work. 
this is my fonts
[supermarket.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/1424952/supermarket.zip)

**Comment by sphilee** [comment]
[defaultVFS.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/1424953/defaultVFS.zip)


um...  It seems like the internet is slow. You can download this.

**Comment by xeleniumz** [comment]
I got the same error. when try to use supermarket fonts
![1](https://user-images.githubusercontent.com/9983597/32142902-b523e1ee-bcd3-11e7-818f-c0afd815c689.png)

**Comment by sphilee** [comment]
[jsPDF-CustomFonts-support.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/1424968/jsPDF-CustomFonts-support.zip)

Would you check this?

**Comment by xeleniumz** [comment]
now it doesn't has error but when i was test with thai language it shows
##!'4"L 
in pdf file
you can copy the code below to test
`
<script>
        var doc = new jsPDF();

        doc.addFont('supermarket.ttf', 'supermarket', 'normal');

        doc.setFont('supermarket');
        doc.text(15, 15, 'สวัสดี ยินดีที่ได้รู้จักคุณ');

        doc.save('custom_fonts.pdf');
    </script>
`

**Comment by sphilee** [comment]
[jsPDF-CustomFonts-support.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/1424991/jsPDF-CustomFonts-support.zip)

**Comment by xeleniumz** [comment]
@sphilee  Thank you for your help now it's work
p.s sorry for my bad grammar

**Comment by xeleniumz** [comment]
i forgot to ask you about how to fix it. would you like to explain ? because sometimes i need to change fonts

**Comment by sphilee** [comment]
1. you have to encode to base64
<https://www.giftofspeed.com/base64-encoder/>.

Once you have the base64 code of your font you have to go to the defaultVFS.js
file that you have download with the jsPDF-CustomFonts-support
<https://github.com/sphilee/jsPDF-CustomFonts-support>  and after one of
the '*,*' used to separate the different fonts in that file you have to add:

"Roboto.ttf":"*your base64 code goes here*", (remeber to finish with a coma
at the end, after the quotes).

Once you do that you can add the function doc.
addFont("Roboto.ttf","Roboto","normal").

It can be a little confusing.

I hope this helps.

**Comment by xeleniumz** [comment]
@sphilee . sorry for late reply. now it's work !!. Thank you for your advice
