### ISSUE TITLE
reopen issue: https://github.com/sphilee/jsPDF-CustomFonts-support/issues/20

### ISSUE THREAD

**Issue by karlog100** [sphilee/jsPDF-CustomFonts-support#22]
Hello

I have created the issue: https://github.com/sphilee/jsPDF-CustomFonts-support/issues/20 but did not see the reply in time, and the issue is now marked as closed, but I still have the issue.

Please take a look at my reply.

**Comment by sphilee** [comment]
@karlog100 Thanks for the error.

I just fixed the code. Check it out.

**Comment by karlog100** [comment]
You are a lifesaver!

It looks to fully work! Thanks
