### ISSUE TITLE
Cannot read property 'widths' of undefined

### ISSUE THREAD

**Issue by kentastudillo** [sphilee/jsPDF-CustomFonts-support#27]
I am trying to center the text but I am getting this error when using the function **getStringUnitWidth**. 
I already included the required plugins:
- split_text_to_size.js

When I use the script from [jsPDF](https://github.com/MrRio/jsPDF), the error disappears but the font doesn't work.

**Comment by Hlkz** [comment]
+1
If somenone has an idea about this, would be great

**Comment by sphilee** [comment]
Could you give me a font name and sample code? I'll check it out.

**Comment by Hlkz** [comment]
Here 
`  let doc = new jsPDF('p', 'pt')
  doc.addFont('340B7A_C_0.ttf', 'PlutoSansCondLight', 'normal')
  doc.setFont('PlutoSansCondLight')
  doc.setFontSize(16)
  console.log(doc.getStringUnitWidth('Text'))`
[default_vfs.zip](https://github.com/sphilee/jsPDF-CustomFonts-support/files/1488172/default_vfs.zip)

If setFont('Arial') there are no error, console : 1.8199999999999998.

Thank you

**Comment by AmyHawkes** [comment]
+1

Any luck with this issue?

**Comment by sphilee** [comment]
Could you check it again?

**Comment by AmyHawkes** [comment]
Yep, that's fixed it for me! Thanks a bunch.
