### ISSUE TITLE
Additional information if custom font has not been imported

### ISSUE THREAD

**Issue by patrykbialek** [sphilee/jsPDF-CustomFonts-support#31]
I started to use that great library within my Angular 4+ project. After I made a test with 'demo' files I implemented library to my source code.
First usage and error occured. I the end it was a problem with custom font import.

Based on that I propose small improvements, add extra information for Developer who will meet similar problem like me.

**1. extend following push with console.error**

```
jsPDFAPI.events.push(['addFont', function(font) {
    if (jsPDFAPI.existsFileInVFS(font.postScriptName)) {
        font.metadata = TTFFont.open(font.postScriptName, font.fontName, jsPDFAPI.getFileFromVFS(font.postScriptName), font.encoding);
        font.encoding = font.metadata.hmtx.widths.length < 500 && font.metadata.capHeight < 800 ? "WinAnsiEncoding" : "MacRomanEncoding";
    } else {
        if (font.id.slice(1) >= 14)
        console.error(`Font does not exist in FileInVFS, import fonts or remove declaration doc.addFont('${font.postScriptName}').`)
    }
}]);
```
Result
![image](https://user-images.githubusercontent.com/14963609/34064462-680189e8-e1f9-11e7-97af-91cab90636ee.png)

**2. Stop further code execution if missing fonts**
```
var getCharWidthsArray = API.getCharWidthsArray = function(text, options) {

    if (!options) {
        options = {};
    }

    var l = text.length;
    var output = [];
    var i;
    var isEmpty = Object.keys(options.font).length === 0 ? true : false;

    // Stop here if empty
    if (isEmpty) {
        return false;
    }
```

**3. No error with `embedTTF`**
```
putFont = function putFont(font) {
    var noMetadata = Object.keys(font.metadata).length === 0 ? true : false;
    if (font.id.slice(1) >= 14 && !noMetadata) {
        var dictionary = font.metadata.embedTTF(font.encoding, newObject, out);
        dictionary ? font.objectNumber = dictionary : delete fonts[font.id];
    } else {
        font.objectNumber = newObject();
        out('<</BaseFont/' + font.postScriptName + '/Type/Font');
        if (typeof font.encoding === 'string') {
            out('/Encoding/' + font.encoding);
        }
        out('/Subtype/Type1>>');
        out('endobj');
    }
},
```

**Comment by sphilee** [comment]
@patrykbialek Thank you very much for informing me. I'll apply your code.

**Comment by patrykbialek** [comment]
@sphilee Mhm, Yes, you are right. I didn't make enough test, and check only case with custom font :(
I will check it later and will back soon with some other proposal for option 2.

**Comment by patrykbialek** [comment]
@sphilee So, new version below.

Tested with 3 cases:
1. use only default font
2. add custom font (addFont(...)) which is not imported
3. add custom font (addFont(...)) which is imported 

Comment: additional check `                if (isNotEmpty) {` prevents showing the error related to `widthOfString` for case 2 mentioned above.

Code:
```
if (options.font) {
    var fontSize = options.fontSize;
    var charSpace = options.charSpace;
    var isNotEmpty = Object.keys(options.font).length > 0 ? true : false;
    
    if (isNotEmpty) {
        for (i = 0; i < l; i++) {
            output.push(options.font.widthOfString(text[i], fontSize, charSpace) / fontSize);
        }
    }
    return output;
}
```


Ps. probably we (the team) will use Your library to generate some document preview. Initially we implemented server side approach but comparing to jsPDF solution it's big different. Server side soution requires at least 4 places where we must store the source code and maintain. With jsPDF we have everything in 1 place (js/ts file).
Thank you, good job.

**Comment by sphilee** [comment]
@patrykbialek It 's an honor for you to use my library. And I've applied some modifications to your code. Thanks for leaving issues and code :)

**Comment by patrykbialek** [comment]
Thanks again.

**Comment by charleskhenry** [comment]
I'm having this exact issue.  And I'm very confused.
