### ISSUE TITLE
Text alignment `right`and `center` not working

### ISSUE THREAD

**Issue by Niekes** [sphilee/jsPDF-CustomFonts-support#42]
if you change the 6th line at the demo page to
`doc.text(90, 15, 'こんにちは。はじめまして。', null, null, 'right');`
the font looks kind of strange.

If you change the font to helvetica, the alignment works as aspected.

**Comment by sphilee** [comment]
@Niekes I just fixed it. Please check.

**Comment by Niekes** [comment]
THANK YOU!
