### ISSUE TITLE
Multiline Text is not supported with drawText

### ISSUE THREAD

**Issue by ashakoshti1988** [sphilee/jsPDF-CustomFonts-support#5]
As per code with multiline text it only changes X values everytime but the Y value remains same which create overflow.
but does not support linebreak like API.Text()

**Comment by saurabhgis** [comment]
is it support urdu font.

**Comment by olsn** [comment]
I had the same issue - I've adjusted the following:

In `pageOut(...)` adjust the return-value:
```
// x, y, width, height + padding of 1.8
return [x, y, tmpsum, (fontSize + 1.8) * lineHeightProportion];
```

and in `drawText` adjust the calls(3) of `pageOut(...)`:
```
axisCache = pageOut(text[i], fontSize, key, Color, charSpace, 0/* was 'sum' */, x, y);
// sum = axisCache[0]; // not needed for vertical linebreaks
y = axisCache[1] + axisCache[3]; // update 'y' to the last 'y' + the returned lineHeight
```

**Comment by sphilee** [comment]
I just edited it. Can you check it?
