### ISSUE TITLE
How does this plugin support Chinese？

### ISSUE THREAD

**Issue by ZhouM1118** [sphilee/jsPDF-CustomFonts-support#9]
This plugin does not seem to support Chinese，How does this plugin support Chinese, what should I do?

**Comment by sphilee** [comment]
`doc.setFont('LiLing');`
'doc.drawText(10, 20, '早晨好。认识你很高兴。');'

I just changed. HanWang font did not support some characters. Using the LiLing font will be all right.

**Comment by ZhouM1118** [comment]
@sphilee thx! Its works!
